apiVersion: v1
kind: Secret
metadata:
  name: dtm-db-secret
type: Opaque
stringData:
  username: "dtm"
  password: "dtm-demo-password" # change to actual db password
  config.yaml: |-
    store:
      Driver: postgres
      Host: dtm-db
      Port: 5432
      User: dtm
      Password: dtm-demo-password
      Db: dtm
