apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - postgres-pvc.yaml
  - postgres.yaml
  - dtm-secret.yaml
  - dtm.yaml
  - behavior-config.yaml

patches:
  - target:
      kind: Deployment
      name: inventoryservice
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: inventoryservice
      spec:
        template:
          spec:
            containers:
              - name: server
                imagePullPolicy: Always
                volumeMounts:
                  - name: behavior-volume
                    mountPath: /var/behavior-config
            volumes:
              - name: behavior-volume
                configMap:
                  name: service-behavior
  - target:
      kind: Deployment
      name: warehousemanagement
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: warehousemanagement
      spec:
        template:
          spec:
            containers:
              - name: server
                imagePullPolicy: Always
                volumeMounts:
                  - name: behavior-volume
                    mountPath: /var/behavior-config
            volumes:
              - name: behavior-volume
                configMap:
                  name: service-behavior
