apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

nameSuffix: -naive

patches:
  - path: naive-patch.yaml
  - target:
      kind: Service
      name: warehouse-management-nodeport
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30051
