apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    spec:
      initContainers:
        - name: wait-for-mqtt
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z mqtt-broker 1883; do
                echo "Waiting for MQTT broker..."
                sleep 2
              done
              echo "MQTT broker is ready."
      containers:
        - name: server
          env:
            - name: MQTT_BROKER_ADDR
              value: "mqtt-broker:1883"
