// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: warehousemanagement/warehousemanagement.proto

package warehousemanagementpb

import (
	context "context"
	inventory "github.com/turt1z/microservices-demo/src/warehousemanagement/genproto/inventory"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WarehouseManagement_UpdateProductStock_FullMethodName = "/warehouse.management.WarehouseManagement/UpdateProductStock"
	WarehouseManagement_CreateNewProduct_FullMethodName   = "/warehouse.management.WarehouseManagement/CreateNewProduct"
)

// WarehouseManagementClient is the client API for WarehouseManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WarehouseManagementClient interface {
	UpdateProductStock(ctx context.Context, in *inventory.ChangeInventoryProductStockRequest, opts ...grpc.CallOption) (*inventory.InventoryProduct, error)
	CreateNewProduct(ctx context.Context, in *CreateWarehouseProductRequest, opts ...grpc.CallOption) (*CreateWarehouseProductResponse, error)
}

type warehouseManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewWarehouseManagementClient(cc grpc.ClientConnInterface) WarehouseManagementClient {
	return &warehouseManagementClient{cc}
}

func (c *warehouseManagementClient) UpdateProductStock(ctx context.Context, in *inventory.ChangeInventoryProductStockRequest, opts ...grpc.CallOption) (*inventory.InventoryProduct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(inventory.InventoryProduct)
	err := c.cc.Invoke(ctx, WarehouseManagement_UpdateProductStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseManagementClient) CreateNewProduct(ctx context.Context, in *CreateWarehouseProductRequest, opts ...grpc.CallOption) (*CreateWarehouseProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWarehouseProductResponse)
	err := c.cc.Invoke(ctx, WarehouseManagement_CreateNewProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WarehouseManagementServer is the server API for WarehouseManagement service.
// All implementations must embed UnimplementedWarehouseManagementServer
// for forward compatibility.
type WarehouseManagementServer interface {
	UpdateProductStock(context.Context, *inventory.ChangeInventoryProductStockRequest) (*inventory.InventoryProduct, error)
	CreateNewProduct(context.Context, *CreateWarehouseProductRequest) (*CreateWarehouseProductResponse, error)
	mustEmbedUnimplementedWarehouseManagementServer()
}

// UnimplementedWarehouseManagementServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWarehouseManagementServer struct{}

func (UnimplementedWarehouseManagementServer) UpdateProductStock(context.Context, *inventory.ChangeInventoryProductStockRequest) (*inventory.InventoryProduct, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProductStock not implemented")
}
func (UnimplementedWarehouseManagementServer) CreateNewProduct(context.Context, *CreateWarehouseProductRequest) (*CreateWarehouseProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNewProduct not implemented")
}
func (UnimplementedWarehouseManagementServer) mustEmbedUnimplementedWarehouseManagementServer() {}
func (UnimplementedWarehouseManagementServer) testEmbeddedByValue()                             {}

// UnsafeWarehouseManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WarehouseManagementServer will
// result in compilation errors.
type UnsafeWarehouseManagementServer interface {
	mustEmbedUnimplementedWarehouseManagementServer()
}

func RegisterWarehouseManagementServer(s grpc.ServiceRegistrar, srv WarehouseManagementServer) {
	// If the following call panics, it indicates UnimplementedWarehouseManagementServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WarehouseManagement_ServiceDesc, srv)
}

func _WarehouseManagement_UpdateProductStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(inventory.ChangeInventoryProductStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseManagementServer).UpdateProductStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseManagement_UpdateProductStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseManagementServer).UpdateProductStock(ctx, req.(*inventory.ChangeInventoryProductStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseManagement_CreateNewProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWarehouseProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseManagementServer).CreateNewProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseManagement_CreateNewProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseManagementServer).CreateNewProduct(ctx, req.(*CreateWarehouseProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WarehouseManagement_ServiceDesc is the grpc.ServiceDesc for WarehouseManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WarehouseManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "warehouse.management.WarehouseManagement",
	HandlerType: (*WarehouseManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateProductStock",
			Handler:    _WarehouseManagement_UpdateProductStock_Handler,
		},
		{
			MethodName: "CreateNewProduct",
			Handler:    _WarehouseManagement_CreateNewProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "warehousemanagement/warehousemanagement.proto",
}
