# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification/notification.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'notification/notification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from reorderservice.generated_proto.checkout import checkout_pb2 as checkout_dot_checkout__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fnotification/notification.proto\x12\x0bhipstershop\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17\x63heckout/checkout.proto\"+\n\x15ListOpenAlertsRequest\x12\x12\n\ncategories\x18\x01 \x03(\t\"\x83\x01\n\nStockAlert\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x03(\t\x12\r\n\x05stock\x18\x03 \x01(\x03\x12\x10\n\x08severity\x18\x04 \x01(\t\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"A\n\x16ListOpenAlertsResponse\x12\'\n\x06\x61lerts\x18\x01 \x03(\x0b\x32\x17.hipstershop.StockAlert\".\n\x18StreamStockAlertsRequest\x12\x12\n\ncategories\x18\x01 \x03(\t\"7\n!ListRecentOrdersByCurrencyRequest\x12\x12\n\ncurrencies\x18\x01 \x03(\t\"5\n\tOrderList\x12(\n\x06orders\x18\x01 \x03(\x0b\x32\x18.hipstershop.OrderResult\"\xd8\x01\n\"ListRecentOrdersByCurrencyResponse\x12\x61\n\x12orders_by_currency\x18\x01 \x03(\x0b\x32\x45.hipstershop.ListRecentOrdersByCurrencyResponse.OrdersByCurrencyEntry\x1aO\n\x15OrdersByCurrencyEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.hipstershop.OrderList:\x02\x38\x01\x32\xcc\x02\n\x13NotificationService\x12[\n\x0eListOpenAlerts\x12\".hipstershop.ListOpenAlertsRequest\x1a#.hipstershop.ListOpenAlertsResponse\"\x00\x12W\n\x11StreamStockAlerts\x12%.hipstershop.StreamStockAlertsRequest\x1a\x17.hipstershop.StockAlert\"\x00\x30\x01\x12\x7f\n\x1aListRecentOrdersByCurrency\x12..hipstershop.ListRecentOrdersByCurrencyRequest\x1a/.hipstershop.ListRecentOrdersByCurrencyResponse\"\x00\x42\x45ZCgithub.com/netd-tud/ds-onlineshop/proto/notification;notificationpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification.notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZCgithub.com/netd-tud/ds-onlineshop/proto/notification;notificationpb'
  _globals['_LISTRECENTORDERSBYCURRENCYRESPONSE_ORDERSBYCURRENCYENTRY']._loaded_options = None
  _globals['_LISTRECENTORDERSBYCURRENCYRESPONSE_ORDERSBYCURRENCYENTRY']._serialized_options = b'8\001'
  _globals['_LISTOPENALERTSREQUEST']._serialized_start=106
  _globals['_LISTOPENALERTSREQUEST']._serialized_end=149
  _globals['_STOCKALERT']._serialized_start=152
  _globals['_STOCKALERT']._serialized_end=283
  _globals['_LISTOPENALERTSRESPONSE']._serialized_start=285
  _globals['_LISTOPENALERTSRESPONSE']._serialized_end=350
  _globals['_STREAMSTOCKALERTSREQUEST']._serialized_start=352
  _globals['_STREAMSTOCKALERTSREQUEST']._serialized_end=398
  _globals['_LISTRECENTORDERSBYCURRENCYREQUEST']._serialized_start=400
  _globals['_LISTRECENTORDERSBYCURRENCYREQUEST']._serialized_end=455
  _globals['_ORDERLIST']._serialized_start=457
  _globals['_ORDERLIST']._serialized_end=510
  _globals['_LISTRECENTORDERSBYCURRENCYRESPONSE']._serialized_start=513
  _globals['_LISTRECENTORDERSBYCURRENCYRESPONSE']._serialized_end=729
  _globals['_LISTRECENTORDERSBYCURRENCYRESPONSE_ORDERSBYCURRENCYENTRY']._serialized_start=650
  _globals['_LISTRECENTORDERSBYCURRENCYRESPONSE_ORDERSBYCURRENCYENTRY']._serialized_end=729
  _globals['_NOTIFICATIONSERVICE']._serialized_start=732
  _globals['_NOTIFICATIONSERVICE']._serialized_end=1064
# @@protoc_insertion_point(module_scope)
