// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: notification/notification.proto

package notificationpb

import (
	checkout "github.com/netd-tud/ds-onlineshop/src/notificationservice/genproto/checkout"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListOpenAlertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []string               `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOpenAlertsRequest) Reset() {
	*x = ListOpenAlertsRequest{}
	mi := &file_notification_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOpenAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOpenAlertsRequest) ProtoMessage() {}

func (x *ListOpenAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOpenAlertsRequest.ProtoReflect.Descriptor instead.
func (*ListOpenAlertsRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{0}
}

func (x *ListOpenAlertsRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

type StockAlert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Category      []string               `protobuf:"bytes,2,rep,name=category,proto3" json:"category,omitempty"`
	Stock         int64                  `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockAlert) Reset() {
	*x = StockAlert{}
	mi := &file_notification_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockAlert) ProtoMessage() {}

func (x *StockAlert) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockAlert.ProtoReflect.Descriptor instead.
func (*StockAlert) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{1}
}

func (x *StockAlert) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StockAlert) GetCategory() []string {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *StockAlert) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *StockAlert) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *StockAlert) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListOpenAlertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*StockAlert          `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOpenAlertsResponse) Reset() {
	*x = ListOpenAlertsResponse{}
	mi := &file_notification_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOpenAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOpenAlertsResponse) ProtoMessage() {}

func (x *ListOpenAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOpenAlertsResponse.ProtoReflect.Descriptor instead.
func (*ListOpenAlertsResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{2}
}

func (x *ListOpenAlertsResponse) GetAlerts() []*StockAlert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

type StreamStockAlertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []string               `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStockAlertsRequest) Reset() {
	*x = StreamStockAlertsRequest{}
	mi := &file_notification_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStockAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStockAlertsRequest) ProtoMessage() {}

func (x *StreamStockAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStockAlertsRequest.ProtoReflect.Descriptor instead.
func (*StreamStockAlertsRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{3}
}

func (x *StreamStockAlertsRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

type ListRecentOrdersByCurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currencies    []string               `protobuf:"bytes,1,rep,name=currencies,proto3" json:"currencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecentOrdersByCurrencyRequest) Reset() {
	*x = ListRecentOrdersByCurrencyRequest{}
	mi := &file_notification_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecentOrdersByCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecentOrdersByCurrencyRequest) ProtoMessage() {}

func (x *ListRecentOrdersByCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecentOrdersByCurrencyRequest.ProtoReflect.Descriptor instead.
func (*ListRecentOrdersByCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{4}
}

func (x *ListRecentOrdersByCurrencyRequest) GetCurrencies() []string {
	if x != nil {
		return x.Currencies
	}
	return nil
}

type OrderList struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Orders        []*checkout.OrderResult `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderList) Reset() {
	*x = OrderList{}
	mi := &file_notification_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderList) ProtoMessage() {}

func (x *OrderList) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderList.ProtoReflect.Descriptor instead.
func (*OrderList) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{5}
}

func (x *OrderList) GetOrders() []*checkout.OrderResult {
	if x != nil {
		return x.Orders
	}
	return nil
}

type ListRecentOrdersByCurrencyResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrdersByCurrency map[string]*OrderList  `protobuf:"bytes,1,rep,name=orders_by_currency,json=ordersByCurrency,proto3" json:"orders_by_currency,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListRecentOrdersByCurrencyResponse) Reset() {
	*x = ListRecentOrdersByCurrencyResponse{}
	mi := &file_notification_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecentOrdersByCurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecentOrdersByCurrencyResponse) ProtoMessage() {}

func (x *ListRecentOrdersByCurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecentOrdersByCurrencyResponse.ProtoReflect.Descriptor instead.
func (*ListRecentOrdersByCurrencyResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{6}
}

func (x *ListRecentOrdersByCurrencyResponse) GetOrdersByCurrency() map[string]*OrderList {
	if x != nil {
		return x.OrdersByCurrency
	}
	return nil
}

var File_notification_notification_proto protoreflect.FileDescriptor

const file_notification_notification_proto_rawDesc = "" +
	"\n" +
	"\x1fnotification/notification.proto\x12\vhipstershop\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17checkout/checkout.proto\"7\n" +
	"\x15ListOpenAlertsRequest\x12\x1e\n" +
	"\n" +
	"categories\x18\x01 \x03(\tR\n" +
	"categories\"\xb4\x01\n" +
	"\n" +
	"StockAlert\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bcategory\x18\x02 \x03(\tR\bcategory\x12\x14\n" +
	"\x05stock\x18\x03 \x01(\x03R\x05stock\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"I\n" +
	"\x16ListOpenAlertsResponse\x12/\n" +
	"\x06alerts\x18\x01 \x03(\v2\x17.hipstershop.StockAlertR\x06alerts\":\n" +
	"\x18StreamStockAlertsRequest\x12\x1e\n" +
	"\n" +
	"categories\x18\x01 \x03(\tR\n" +
	"categories\"C\n" +
	"!ListRecentOrdersByCurrencyRequest\x12\x1e\n" +
	"\n" +
	"currencies\x18\x01 \x03(\tR\n" +
	"currencies\"=\n" +
	"\tOrderList\x120\n" +
	"\x06orders\x18\x01 \x03(\v2\x18.hipstershop.OrderResultR\x06orders\"\xf6\x01\n" +
	"\"ListRecentOrdersByCurrencyResponse\x12s\n" +
	"\x12orders_by_currency\x18\x01 \x03(\v2E.hipstershop.ListRecentOrdersByCurrencyResponse.OrdersByCurrencyEntryR\x10ordersByCurrency\x1a[\n" +
	"\x15OrdersByCurrencyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.hipstershop.OrderListR\x05value:\x028\x012\xcc\x02\n" +
	"\x13NotificationService\x12[\n" +
	"\x0eListOpenAlerts\x12\".hipstershop.ListOpenAlertsRequest\x1a#.hipstershop.ListOpenAlertsResponse\"\x00\x12W\n" +
	"\x11StreamStockAlerts\x12%.hipstershop.StreamStockAlertsRequest\x1a\x17.hipstershop.StockAlert\"\x000\x01\x12\x7f\n" +
	"\x1aListRecentOrdersByCurrency\x12..hipstershop.ListRecentOrdersByCurrencyRequest\x1a/.hipstershop.ListRecentOrdersByCurrencyResponse\"\x00BEZCgithub.com/netd-tud/ds-onlineshop/proto/notification;notificationpbb\x06proto3"

var (
	file_notification_notification_proto_rawDescOnce sync.Once
	file_notification_notification_proto_rawDescData []byte
)

func file_notification_notification_proto_rawDescGZIP() []byte {
	file_notification_notification_proto_rawDescOnce.Do(func() {
		file_notification_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_notification_proto_rawDesc), len(file_notification_notification_proto_rawDesc)))
	})
	return file_notification_notification_proto_rawDescData
}

var file_notification_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_notification_notification_proto_goTypes = []any{
	(*ListOpenAlertsRequest)(nil),              // 0: hipstershop.ListOpenAlertsRequest
	(*StockAlert)(nil),                         // 1: hipstershop.StockAlert
	(*ListOpenAlertsResponse)(nil),             // 2: hipstershop.ListOpenAlertsResponse
	(*StreamStockAlertsRequest)(nil),           // 3: hipstershop.StreamStockAlertsRequest
	(*ListRecentOrdersByCurrencyRequest)(nil),  // 4: hipstershop.ListRecentOrdersByCurrencyRequest
	(*OrderList)(nil),                          // 5: hipstershop.OrderList
	(*ListRecentOrdersByCurrencyResponse)(nil), // 6: hipstershop.ListRecentOrdersByCurrencyResponse
	nil,                           // 7: hipstershop.ListRecentOrdersByCurrencyResponse.OrdersByCurrencyEntry
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*checkout.OrderResult)(nil),  // 9: hipstershop.OrderResult
}
var file_notification_notification_proto_depIdxs = []int32{
	8, // 0: hipstershop.StockAlert.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: hipstershop.ListOpenAlertsResponse.alerts:type_name -> hipstershop.StockAlert
	9, // 2: hipstershop.OrderList.orders:type_name -> hipstershop.OrderResult
	7, // 3: hipstershop.ListRecentOrdersByCurrencyResponse.orders_by_currency:type_name -> hipstershop.ListRecentOrdersByCurrencyResponse.OrdersByCurrencyEntry
	5, // 4: hipstershop.ListRecentOrdersByCurrencyResponse.OrdersByCurrencyEntry.value:type_name -> hipstershop.OrderList
	0, // 5: hipstershop.NotificationService.ListOpenAlerts:input_type -> hipstershop.ListOpenAlertsRequest
	3, // 6: hipstershop.NotificationService.StreamStockAlerts:input_type -> hipstershop.StreamStockAlertsRequest
	4, // 7: hipstershop.NotificationService.ListRecentOrdersByCurrency:input_type -> hipstershop.ListRecentOrdersByCurrencyRequest
	2, // 8: hipstershop.NotificationService.ListOpenAlerts:output_type -> hipstershop.ListOpenAlertsResponse
	1, // 9: hipstershop.NotificationService.StreamStockAlerts:output_type -> hipstershop.StockAlert
	6, // 10: hipstershop.NotificationService.ListRecentOrdersByCurrency:output_type -> hipstershop.ListRecentOrdersByCurrencyResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_notification_notification_proto_init() }
func file_notification_notification_proto_init() {
	if File_notification_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_notification_proto_rawDesc), len(file_notification_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_notification_proto_goTypes,
		DependencyIndexes: file_notification_notification_proto_depIdxs,
		MessageInfos:      file_notification_notification_proto_msgTypes,
	}.Build()
	File_notification_notification_proto = out.File
	file_notification_notification_proto_goTypes = nil
	file_notification_notification_proto_depIdxs = nil
}
