// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: notification/notification.proto

package notificationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListOpenAlertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []string               `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOpenAlertsRequest) Reset() {
	*x = ListOpenAlertsRequest{}
	mi := &file_notification_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOpenAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOpenAlertsRequest) ProtoMessage() {}

func (x *ListOpenAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOpenAlertsRequest.ProtoReflect.Descriptor instead.
func (*ListOpenAlertsRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{0}
}

func (x *ListOpenAlertsRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

type StockAlert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Category      []string               `protobuf:"bytes,2,rep,name=category,proto3" json:"category,omitempty"`
	Stock         int64                  `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockAlert) Reset() {
	*x = StockAlert{}
	mi := &file_notification_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockAlert) ProtoMessage() {}

func (x *StockAlert) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockAlert.ProtoReflect.Descriptor instead.
func (*StockAlert) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{1}
}

func (x *StockAlert) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StockAlert) GetCategory() []string {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *StockAlert) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *StockAlert) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

type ListOpenAlertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*StockAlert          `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOpenAlertsResponse) Reset() {
	*x = ListOpenAlertsResponse{}
	mi := &file_notification_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOpenAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOpenAlertsResponse) ProtoMessage() {}

func (x *ListOpenAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOpenAlertsResponse.ProtoReflect.Descriptor instead.
func (*ListOpenAlertsResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{2}
}

func (x *ListOpenAlertsResponse) GetAlerts() []*StockAlert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

var File_notification_notification_proto protoreflect.FileDescriptor

const file_notification_notification_proto_rawDesc = "" +
	"\n" +
	"\x1fnotification/notification.proto\x12\vhipstershop\"7\n" +
	"\x15ListOpenAlertsRequest\x12\x1e\n" +
	"\n" +
	"categories\x18\x01 \x03(\tR\n" +
	"categories\"y\n" +
	"\n" +
	"StockAlert\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bcategory\x18\x02 \x03(\tR\bcategory\x12\x14\n" +
	"\x05stock\x18\x03 \x01(\x03R\x05stock\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\"I\n" +
	"\x16ListOpenAlertsResponse\x12/\n" +
	"\x06alerts\x18\x01 \x03(\v2\x17.hipstershop.StockAlertR\x06alerts2r\n" +
	"\x13NotificationService\x12[\n" +
	"\x0eListOpenAlerts\x12\".hipstershop.ListOpenAlertsRequest\x1a#.hipstershop.ListOpenAlertsResponse\"\x00BEZCgithub.com/netd-tud/ds-onlineshop/proto/notification;notificationpbb\x06proto3"

var (
	file_notification_notification_proto_rawDescOnce sync.Once
	file_notification_notification_proto_rawDescData []byte
)

func file_notification_notification_proto_rawDescGZIP() []byte {
	file_notification_notification_proto_rawDescOnce.Do(func() {
		file_notification_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_notification_proto_rawDesc), len(file_notification_notification_proto_rawDesc)))
	})
	return file_notification_notification_proto_rawDescData
}

var file_notification_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_notification_notification_proto_goTypes = []any{
	(*ListOpenAlertsRequest)(nil),  // 0: hipstershop.ListOpenAlertsRequest
	(*StockAlert)(nil),             // 1: hipstershop.StockAlert
	(*ListOpenAlertsResponse)(nil), // 2: hipstershop.ListOpenAlertsResponse
}
var file_notification_notification_proto_depIdxs = []int32{
	1, // 0: hipstershop.ListOpenAlertsResponse.alerts:type_name -> hipstershop.StockAlert
	0, // 1: hipstershop.NotificationService.ListOpenAlerts:input_type -> hipstershop.ListOpenAlertsRequest
	2, // 2: hipstershop.NotificationService.ListOpenAlerts:output_type -> hipstershop.ListOpenAlertsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_notification_notification_proto_init() }
func file_notification_notification_proto_init() {
	if File_notification_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_notification_proto_rawDesc), len(file_notification_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_notification_proto_goTypes,
		DependencyIndexes: file_notification_notification_proto_depIdxs,
		MessageInfos:      file_notification_notification_proto_msgTypes,
	}.Build()
	File_notification_notification_proto = out.File
	file_notification_notification_proto_goTypes = nil
	file_notification_notification_proto_depIdxs = nil
}
