// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: notification/notification.proto

package notificationpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotificationService_ListOpenAlerts_FullMethodName             = "/hipstershop.NotificationService/ListOpenAlerts"
	NotificationService_StreamStockAlerts_FullMethodName          = "/hipstershop.NotificationService/StreamStockAlerts"
	NotificationService_ListRecentOrdersByCurrency_FullMethodName = "/hipstershop.NotificationService/ListRecentOrdersByCurrency"
)

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationServiceClient interface {
	ListOpenAlerts(ctx context.Context, in *ListOpenAlertsRequest, opts ...grpc.CallOption) (*ListOpenAlertsResponse, error)
	StreamStockAlerts(ctx context.Context, in *StreamStockAlertsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StockAlert], error)
	ListRecentOrdersByCurrency(ctx context.Context, in *ListRecentOrdersByCurrencyRequest, opts ...grpc.CallOption) (*ListRecentOrdersByCurrencyResponse, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) ListOpenAlerts(ctx context.Context, in *ListOpenAlertsRequest, opts ...grpc.CallOption) (*ListOpenAlertsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOpenAlertsResponse)
	err := c.cc.Invoke(ctx, NotificationService_ListOpenAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) StreamStockAlerts(ctx context.Context, in *StreamStockAlertsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StockAlert], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NotificationService_ServiceDesc.Streams[0], NotificationService_StreamStockAlerts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamStockAlertsRequest, StockAlert]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NotificationService_StreamStockAlertsClient = grpc.ServerStreamingClient[StockAlert]

func (c *notificationServiceClient) ListRecentOrdersByCurrency(ctx context.Context, in *ListRecentOrdersByCurrencyRequest, opts ...grpc.CallOption) (*ListRecentOrdersByCurrencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRecentOrdersByCurrencyResponse)
	err := c.cc.Invoke(ctx, NotificationService_ListRecentOrdersByCurrency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations must embed UnimplementedNotificationServiceServer
// for forward compatibility.
type NotificationServiceServer interface {
	ListOpenAlerts(context.Context, *ListOpenAlertsRequest) (*ListOpenAlertsResponse, error)
	StreamStockAlerts(*StreamStockAlertsRequest, grpc.ServerStreamingServer[StockAlert]) error
	ListRecentOrdersByCurrency(context.Context, *ListRecentOrdersByCurrencyRequest) (*ListRecentOrdersByCurrencyResponse, error)
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationServiceServer struct{}

func (UnimplementedNotificationServiceServer) ListOpenAlerts(context.Context, *ListOpenAlertsRequest) (*ListOpenAlertsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOpenAlerts not implemented")
}
func (UnimplementedNotificationServiceServer) StreamStockAlerts(*StreamStockAlertsRequest, grpc.ServerStreamingServer[StockAlert]) error {
	return status.Error(codes.Unimplemented, "method StreamStockAlerts not implemented")
}
func (UnimplementedNotificationServiceServer) ListRecentOrdersByCurrency(context.Context, *ListRecentOrdersByCurrencyRequest) (*ListRecentOrdersByCurrencyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRecentOrdersByCurrency not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}
func (UnimplementedNotificationServiceServer) testEmbeddedByValue()                             {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	// If the following call panics, it indicates UnimplementedNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_ListOpenAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOpenAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).ListOpenAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_ListOpenAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).ListOpenAlerts(ctx, req.(*ListOpenAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_StreamStockAlerts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamStockAlertsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NotificationServiceServer).StreamStockAlerts(m, &grpc.GenericServerStream[StreamStockAlertsRequest, StockAlert]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NotificationService_StreamStockAlertsServer = grpc.ServerStreamingServer[StockAlert]

func _NotificationService_ListRecentOrdersByCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecentOrdersByCurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).ListRecentOrdersByCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_ListRecentOrdersByCurrency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).ListRecentOrdersByCurrency(ctx, req.(*ListRecentOrdersByCurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hipstershop.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListOpenAlerts",
			Handler:    _NotificationService_ListOpenAlerts_Handler,
		},
		{
			MethodName: "ListRecentOrdersByCurrency",
			Handler:    _NotificationService_ListRecentOrdersByCurrency_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamStockAlerts",
			Handler:       _NotificationService_StreamStockAlerts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "notification/notification.proto",
}
