// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: inventory/inventory.proto

package inventorypb

import (
	common "github.com/turt1z/microservices-demo/src/warehousemanagement/genproto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InventoryProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Stock         int64                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryProduct) Reset() {
	*x = InventoryProduct{}
	mi := &file_inventory_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryProduct) ProtoMessage() {}

func (x *InventoryProduct) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryProduct.ProtoReflect.Descriptor instead.
func (*InventoryProduct) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *InventoryProduct) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InventoryProduct) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type ListInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*InventoryProduct    `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInventoryResponse) Reset() {
	*x = ListInventoryResponse{}
	mi := &file_inventory_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInventoryResponse) ProtoMessage() {}

func (x *ListInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInventoryResponse.ProtoReflect.Descriptor instead.
func (*ListInventoryResponse) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *ListInventoryResponse) GetProducts() []*InventoryProduct {
	if x != nil {
		return x.Products
	}
	return nil
}

type GetInventoryProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryProductRequest) Reset() {
	*x = GetInventoryProductRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryProductRequest) ProtoMessage() {}

func (x *GetInventoryProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryProductRequest.ProtoReflect.Descriptor instead.
func (*GetInventoryProductRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *GetInventoryProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ChangeInventoryProductStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Delta         int64                  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeInventoryProductStockRequest) Reset() {
	*x = ChangeInventoryProductStockRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeInventoryProductStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeInventoryProductStockRequest) ProtoMessage() {}

func (x *ChangeInventoryProductStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeInventoryProductStockRequest.ProtoReflect.Descriptor instead.
func (*ChangeInventoryProductStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *ChangeInventoryProductStockRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeInventoryProductStockRequest) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type ChangeInventoryProductStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *InventoryProduct      `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeInventoryProductStockResponse) Reset() {
	*x = ChangeInventoryProductStockResponse{}
	mi := &file_inventory_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeInventoryProductStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeInventoryProductStockResponse) ProtoMessage() {}

func (x *ChangeInventoryProductStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeInventoryProductStockResponse.ProtoReflect.Descriptor instead.
func (*ChangeInventoryProductStockResponse) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *ChangeInventoryProductStockResponse) GetProduct() *InventoryProduct {
	if x != nil {
		return x.Product
	}
	return nil
}

type SetInventoryProductStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NewStock      int64                  `protobuf:"varint,2,opt,name=new_stock,json=newStock,proto3" json:"new_stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInventoryProductStockRequest) Reset() {
	*x = SetInventoryProductStockRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInventoryProductStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInventoryProductStockRequest) ProtoMessage() {}

func (x *SetInventoryProductStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInventoryProductStockRequest.ProtoReflect.Descriptor instead.
func (*SetInventoryProductStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *SetInventoryProductStockRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetInventoryProductStockRequest) GetNewStock() int64 {
	if x != nil {
		return x.NewStock
	}
	return 0
}

type SetInventoryProductStockRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *InventoryProduct      `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInventoryProductStockRequestResponse) Reset() {
	*x = SetInventoryProductStockRequestResponse{}
	mi := &file_inventory_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInventoryProductStockRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInventoryProductStockRequestResponse) ProtoMessage() {}

func (x *SetInventoryProductStockRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInventoryProductStockRequestResponse.ProtoReflect.Descriptor instead.
func (*SetInventoryProductStockRequestResponse) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *SetInventoryProductStockRequestResponse) GetProduct() *InventoryProduct {
	if x != nil {
		return x.Product
	}
	return nil
}

type CreateNewInventoryProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InitialStock  int64                  `protobuf:"varint,2,opt,name=initial_stock,json=initialStock,proto3" json:"initial_stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewInventoryProductRequest) Reset() {
	*x = CreateNewInventoryProductRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewInventoryProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewInventoryProductRequest) ProtoMessage() {}

func (x *CreateNewInventoryProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewInventoryProductRequest.ProtoReflect.Descriptor instead.
func (*CreateNewInventoryProductRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *CreateNewInventoryProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateNewInventoryProductRequest) GetInitialStock() int64 {
	if x != nil {
		return x.InitialStock
	}
	return 0
}

type CreateNewInventoryProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *InventoryProduct      `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewInventoryProductResponse) Reset() {
	*x = CreateNewInventoryProductResponse{}
	mi := &file_inventory_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewInventoryProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewInventoryProductResponse) ProtoMessage() {}

func (x *CreateNewInventoryProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewInventoryProductResponse.ProtoReflect.Descriptor instead.
func (*CreateNewInventoryProductResponse) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *CreateNewInventoryProductResponse) GetProduct() *InventoryProduct {
	if x != nil {
		return x.Product
	}
	return nil
}

type DeleteInventoryProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInventoryProductRequest) Reset() {
	*x = DeleteInventoryProductRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInventoryProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInventoryProductRequest) ProtoMessage() {}

func (x *DeleteInventoryProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInventoryProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteInventoryProductRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteInventoryProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteInventoryProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *InventoryProduct      `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInventoryProductResponse) Reset() {
	*x = DeleteInventoryProductResponse{}
	mi := &file_inventory_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInventoryProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInventoryProductResponse) ProtoMessage() {}

func (x *DeleteInventoryProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInventoryProductResponse.ProtoReflect.Descriptor instead.
func (*DeleteInventoryProductResponse) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteInventoryProductResponse) GetProduct() *InventoryProduct {
	if x != nil {
		return x.Product
	}
	return nil
}

type XaPrepareCreateInventoryProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           string                 `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	InitialStock  int64                  `protobuf:"varint,3,opt,name=initial_stock,json=initialStock,proto3" json:"initial_stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XaPrepareCreateInventoryProductRequest) Reset() {
	*x = XaPrepareCreateInventoryProductRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XaPrepareCreateInventoryProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XaPrepareCreateInventoryProductRequest) ProtoMessage() {}

func (x *XaPrepareCreateInventoryProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XaPrepareCreateInventoryProductRequest.ProtoReflect.Descriptor instead.
func (*XaPrepareCreateInventoryProductRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{11}
}

func (x *XaPrepareCreateInventoryProductRequest) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *XaPrepareCreateInventoryProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *XaPrepareCreateInventoryProductRequest) GetInitialStock() int64 {
	if x != nil {
		return x.InitialStock
	}
	return 0
}

var File_inventory_inventory_proto protoreflect.FileDescriptor

const file_inventory_inventory_proto_rawDesc = "" +
	"\n" +
	"\x19inventory/inventory.proto\x12\vhipstershop\x1a\x13common/common.proto\"8\n" +
	"\x10InventoryProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x03R\x05stock\"R\n" +
	"\x15ListInventoryResponse\x129\n" +
	"\bproducts\x18\x01 \x03(\v2\x1d.hipstershop.InventoryProductR\bproducts\",\n" +
	"\x1aGetInventoryProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\"ChangeInventoryProductStockRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x03R\x05delta\"^\n" +
	"#ChangeInventoryProductStockResponse\x127\n" +
	"\aproduct\x18\x01 \x01(\v2\x1d.hipstershop.InventoryProductR\aproduct\"N\n" +
	"\x1fSetInventoryProductStockRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tnew_stock\x18\x02 \x01(\x03R\bnewStock\"b\n" +
	"'SetInventoryProductStockRequestResponse\x127\n" +
	"\aproduct\x18\x01 \x01(\v2\x1d.hipstershop.InventoryProductR\aproduct\"W\n" +
	" CreateNewInventoryProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rinitial_stock\x18\x02 \x01(\x03R\finitialStock\"\\\n" +
	"!CreateNewInventoryProductResponse\x127\n" +
	"\aproduct\x18\x01 \x01(\v2\x1d.hipstershop.InventoryProductR\aproduct\"/\n" +
	"\x1dDeleteInventoryProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Y\n" +
	"\x1eDeleteInventoryProductResponse\x127\n" +
	"\aproduct\x18\x01 \x01(\v2\x1d.hipstershop.InventoryProductR\aproduct\"o\n" +
	"&XaPrepareCreateInventoryProductRequest\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\tR\x03gid\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12#\n" +
	"\rinitial_stock\x18\x03 \x01(\x03R\finitialStock2\xdb\b\n" +
	"\x10InventoryService\x12I\n" +
	"\rListInventory\x12\x12.hipstershop.Empty\x1a\".hipstershop.ListInventoryResponse\"\x00\x12_\n" +
	"\x13GetInventoryProduct\x12'.hipstershop.GetInventoryProductRequest\x1a\x1d.hipstershop.InventoryProduct\"\x00\x12\x82\x01\n" +
	"\x1bChangeInventoryProductStock\x12/.hipstershop.ChangeInventoryProductStockRequest\x1a0.hipstershop.ChangeInventoryProductStockResponse\"\x00\x12\x80\x01\n" +
	"\x18SetInventoryProductStock\x12,.hipstershop.SetInventoryProductStockRequest\x1a4.hipstershop.SetInventoryProductStockRequestResponse\"\x00\x12|\n" +
	"\x19CreateNewInventoryProduct\x12-.hipstershop.CreateNewInventoryProductRequest\x1a..hipstershop.CreateNewInventoryProductResponse\"\x00\x12s\n" +
	"\x16DeleteInventoryProduct\x12*.hipstershop.DeleteInventoryProductRequest\x1a+.hipstershop.DeleteInventoryProductResponse\"\x00\x12\x83\x01\n" +
	"#CompensateCreateNewInventoryProduct\x12-.hipstershop.CreateNewInventoryProductRequest\x1a+.hipstershop.DeleteInventoryProductResponse\"\x00\x12l\n" +
	"\x1fXaPrepareCreateInventoryProduct\x123.hipstershop.XaPrepareCreateInventoryProductRequest\x1a\x12.hipstershop.Empty\"\x00\x12T\n" +
	"\x1eXaCommitCreateInventoryProduct\x12\x1c.hipstershop.XaBranchRequest\x1a\x12.hipstershop.Empty\"\x00\x12V\n" +
	" XaRollbackCreateInventoryProduct\x12\x1c.hipstershop.XaBranchRequest\x1a\x12.hipstershop.Empty\"\x00BBZ@github.com/turt1z/microservices-demo/proto/inventory;inventorypbb\x06proto3"

var (
	file_inventory_inventory_proto_rawDescOnce sync.Once
	file_inventory_inventory_proto_rawDescData []byte
)

func file_inventory_inventory_proto_rawDescGZIP() []byte {
	file_inventory_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_inventory_proto_rawDesc), len(file_inventory_inventory_proto_rawDesc)))
	})
	return file_inventory_inventory_proto_rawDescData
}

var file_inventory_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_inventory_inventory_proto_goTypes = []any{
	(*InventoryProduct)(nil),                        // 0: hipstershop.InventoryProduct
	(*ListInventoryResponse)(nil),                   // 1: hipstershop.ListInventoryResponse
	(*GetInventoryProductRequest)(nil),              // 2: hipstershop.GetInventoryProductRequest
	(*ChangeInventoryProductStockRequest)(nil),      // 3: hipstershop.ChangeInventoryProductStockRequest
	(*ChangeInventoryProductStockResponse)(nil),     // 4: hipstershop.ChangeInventoryProductStockResponse
	(*SetInventoryProductStockRequest)(nil),         // 5: hipstershop.SetInventoryProductStockRequest
	(*SetInventoryProductStockRequestResponse)(nil), // 6: hipstershop.SetInventoryProductStockRequestResponse
	(*CreateNewInventoryProductRequest)(nil),        // 7: hipstershop.CreateNewInventoryProductRequest
	(*CreateNewInventoryProductResponse)(nil),       // 8: hipstershop.CreateNewInventoryProductResponse
	(*DeleteInventoryProductRequest)(nil),           // 9: hipstershop.DeleteInventoryProductRequest
	(*DeleteInventoryProductResponse)(nil),          // 10: hipstershop.DeleteInventoryProductResponse
	(*XaPrepareCreateInventoryProductRequest)(nil),  // 11: hipstershop.XaPrepareCreateInventoryProductRequest
	(*common.Empty)(nil),                            // 12: hipstershop.Empty
	(*common.XaBranchRequest)(nil),                  // 13: hipstershop.XaBranchRequest
}
var file_inventory_inventory_proto_depIdxs = []int32{
	0,  // 0: hipstershop.ListInventoryResponse.products:type_name -> hipstershop.InventoryProduct
	0,  // 1: hipstershop.ChangeInventoryProductStockResponse.product:type_name -> hipstershop.InventoryProduct
	0,  // 2: hipstershop.SetInventoryProductStockRequestResponse.product:type_name -> hipstershop.InventoryProduct
	0,  // 3: hipstershop.CreateNewInventoryProductResponse.product:type_name -> hipstershop.InventoryProduct
	0,  // 4: hipstershop.DeleteInventoryProductResponse.product:type_name -> hipstershop.InventoryProduct
	12, // 5: hipstershop.InventoryService.ListInventory:input_type -> hipstershop.Empty
	2,  // 6: hipstershop.InventoryService.GetInventoryProduct:input_type -> hipstershop.GetInventoryProductRequest
	3,  // 7: hipstershop.InventoryService.ChangeInventoryProductStock:input_type -> hipstershop.ChangeInventoryProductStockRequest
	5,  // 8: hipstershop.InventoryService.SetInventoryProductStock:input_type -> hipstershop.SetInventoryProductStockRequest
	7,  // 9: hipstershop.InventoryService.CreateNewInventoryProduct:input_type -> hipstershop.CreateNewInventoryProductRequest
	9,  // 10: hipstershop.InventoryService.DeleteInventoryProduct:input_type -> hipstershop.DeleteInventoryProductRequest
	7,  // 11: hipstershop.InventoryService.CompensateCreateNewInventoryProduct:input_type -> hipstershop.CreateNewInventoryProductRequest
	11, // 12: hipstershop.InventoryService.XaPrepareCreateInventoryProduct:input_type -> hipstershop.XaPrepareCreateInventoryProductRequest
	13, // 13: hipstershop.InventoryService.XaCommitCreateInventoryProduct:input_type -> hipstershop.XaBranchRequest
	13, // 14: hipstershop.InventoryService.XaRollbackCreateInventoryProduct:input_type -> hipstershop.XaBranchRequest
	1,  // 15: hipstershop.InventoryService.ListInventory:output_type -> hipstershop.ListInventoryResponse
	0,  // 16: hipstershop.InventoryService.GetInventoryProduct:output_type -> hipstershop.InventoryProduct
	4,  // 17: hipstershop.InventoryService.ChangeInventoryProductStock:output_type -> hipstershop.ChangeInventoryProductStockResponse
	6,  // 18: hipstershop.InventoryService.SetInventoryProductStock:output_type -> hipstershop.SetInventoryProductStockRequestResponse
	8,  // 19: hipstershop.InventoryService.CreateNewInventoryProduct:output_type -> hipstershop.CreateNewInventoryProductResponse
	10, // 20: hipstershop.InventoryService.DeleteInventoryProduct:output_type -> hipstershop.DeleteInventoryProductResponse
	10, // 21: hipstershop.InventoryService.CompensateCreateNewInventoryProduct:output_type -> hipstershop.DeleteInventoryProductResponse
	12, // 22: hipstershop.InventoryService.XaPrepareCreateInventoryProduct:output_type -> hipstershop.Empty
	12, // 23: hipstershop.InventoryService.XaCommitCreateInventoryProduct:output_type -> hipstershop.Empty
	12, // 24: hipstershop.InventoryService.XaRollbackCreateInventoryProduct:output_type -> hipstershop.Empty
	15, // [15:25] is the sub-list for method output_type
	5,  // [5:15] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_inventory_inventory_proto_init() }
func file_inventory_inventory_proto_init() {
	if File_inventory_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_inventory_proto_rawDesc), len(file_inventory_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_inventory_proto_msgTypes,
	}.Build()
	File_inventory_inventory_proto = out.File
	file_inventory_inventory_proto_goTypes = nil
	file_inventory_inventory_proto_depIdxs = nil
}
