apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehousemanagement
  labels:
    app: warehousemanagement
spec:
  selector:
    matchLabels:
      app: warehousemanagement
  template:
    metadata:
      labels:
        app: warehousemanagement
    spec:
      serviceAccountName: warehousemanagement
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: server
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: ghcr.io/turt1z/microservices-demo/warehousemanagement:latest
          ports:
            - name: http
              containerPort: 50000
          env:
            - name: PORT
              value: "50000"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "productcatalogservice:3550"
            - name: INVENTORY_CATALOG_SERVICE_ADDR
              value: "inventoryservice:50002"
            - name: WAREHOUSE_MANAGEMENT_SVC_ADDR
              value: "warehousemanagement:50000"
            - name: DTM_SERVICE_ADDR
              value: "dtm-svc:36790"
            - name: MQTT_BROKER_ADDR
              value: "mqtt-broker:1883"
            - name: SERVED_FUNCTION
              value: "NAIVE"
          resources:
            requests:
              cpu: 200m
              memory: 180Mi
            limits:
              cpu: 300m
              memory: 300Mi
          readinessProbe:
            grpc:
              port: 50000
          livenessProbe:
            grpc:
              port: 50000
---
apiVersion: v1
kind: Service
metadata:
  name: warehousemanagement
  labels:
    app: warehousemanagement
spec:
  type: ClusterIP
  selector:
    app: warehousemanagement
  ports:
    - name: http
      port: 50000
      targetPort: 50000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: warehousemanagement
---
apiVersion: v1
kind: Service
metadata:
  name: warehouse-management-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: warehousemanagement
  ports:
    - protocol: TCP
      port: 50000
      targetPort: 50000
      nodePort: 30050
