// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: checkout/checkout.proto

package checkoutpb

import (
	cart "github.com/netd-tud/ds-onlineshop/src/checkoutservice/genproto/cart"
	common "github.com/netd-tud/ds-onlineshop/src/checkoutservice/genproto/common"
	payment "github.com/netd-tud/ds-onlineshop/src/checkoutservice/genproto/payment"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *cart.CartItem         `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Cost          *common.Money          `protobuf:"bytes,2,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_checkout_checkout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_checkout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_checkout_checkout_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetItem() *cart.CartItem {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *OrderItem) GetCost() *common.Money {
	if x != nil {
		return x.Cost
	}
	return nil
}

type OrderResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OrderId            string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ShippingTrackingId string                 `protobuf:"bytes,2,opt,name=shipping_tracking_id,json=shippingTrackingId,proto3" json:"shipping_tracking_id,omitempty"`
	ShippingCost       *common.Money          `protobuf:"bytes,3,opt,name=shipping_cost,json=shippingCost,proto3" json:"shipping_cost,omitempty"`
	ShippingAddress    *common.Address        `protobuf:"bytes,4,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	Items              []*OrderItem           `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OrderResult) Reset() {
	*x = OrderResult{}
	mi := &file_checkout_checkout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResult) ProtoMessage() {}

func (x *OrderResult) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_checkout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResult.ProtoReflect.Descriptor instead.
func (*OrderResult) Descriptor() ([]byte, []int) {
	return file_checkout_checkout_proto_rawDescGZIP(), []int{1}
}

func (x *OrderResult) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderResult) GetShippingTrackingId() string {
	if x != nil {
		return x.ShippingTrackingId
	}
	return ""
}

func (x *OrderResult) GetShippingCost() *common.Money {
	if x != nil {
		return x.ShippingCost
	}
	return nil
}

func (x *OrderResult) GetShippingAddress() *common.Address {
	if x != nil {
		return x.ShippingAddress
	}
	return nil
}

func (x *OrderResult) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type PlaceOrderRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	UserId        string                  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserCurrency  string                  `protobuf:"bytes,2,opt,name=user_currency,json=userCurrency,proto3" json:"user_currency,omitempty"`
	Address       *common.Address         `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Email         string                  `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	CreditCard    *payment.CreditCardInfo `protobuf:"bytes,6,opt,name=credit_card,json=creditCard,proto3" json:"credit_card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderRequest) Reset() {
	*x = PlaceOrderRequest{}
	mi := &file_checkout_checkout_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequest) ProtoMessage() {}

func (x *PlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_checkout_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_checkout_checkout_proto_rawDescGZIP(), []int{2}
}

func (x *PlaceOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlaceOrderRequest) GetUserCurrency() string {
	if x != nil {
		return x.UserCurrency
	}
	return ""
}

func (x *PlaceOrderRequest) GetAddress() *common.Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *PlaceOrderRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PlaceOrderRequest) GetCreditCard() *payment.CreditCardInfo {
	if x != nil {
		return x.CreditCard
	}
	return nil
}

type PlaceOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderResult           `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderResponse) Reset() {
	*x = PlaceOrderResponse{}
	mi := &file_checkout_checkout_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderResponse) ProtoMessage() {}

func (x *PlaceOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_checkout_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderResponse.ProtoReflect.Descriptor instead.
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return file_checkout_checkout_proto_rawDescGZIP(), []int{3}
}

func (x *PlaceOrderResponse) GetOrder() *OrderResult {
	if x != nil {
		return x.Order
	}
	return nil
}

var File_checkout_checkout_proto protoreflect.FileDescriptor

const file_checkout_checkout_proto_rawDesc = "" +
	"\n" +
	"\x17checkout/checkout.proto\x12\vhipstershop\x1a\x13common/common.proto\x1a\x15payment/payment.proto\x1a\x0fcart/cart.proto\"^\n" +
	"\tOrderItem\x12)\n" +
	"\x04item\x18\x01 \x01(\v2\x15.hipstershop.CartItemR\x04item\x12&\n" +
	"\x04cost\x18\x02 \x01(\v2\x12.hipstershop.MoneyR\x04cost\"\x82\x02\n" +
	"\vOrderResult\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x120\n" +
	"\x14shipping_tracking_id\x18\x02 \x01(\tR\x12shippingTrackingId\x127\n" +
	"\rshipping_cost\x18\x03 \x01(\v2\x12.hipstershop.MoneyR\fshippingCost\x12?\n" +
	"\x10shipping_address\x18\x04 \x01(\v2\x14.hipstershop.AddressR\x0fshippingAddress\x12,\n" +
	"\x05items\x18\x05 \x03(\v2\x16.hipstershop.OrderItemR\x05items\"\xd5\x01\n" +
	"\x11PlaceOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\ruser_currency\x18\x02 \x01(\tR\fuserCurrency\x12.\n" +
	"\aaddress\x18\x03 \x01(\v2\x14.hipstershop.AddressR\aaddress\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12<\n" +
	"\vcredit_card\x18\x06 \x01(\v2\x1b.hipstershop.CreditCardInfoR\n" +
	"creditCard\"D\n" +
	"\x12PlaceOrderResponse\x12.\n" +
	"\x05order\x18\x01 \x01(\v2\x18.hipstershop.OrderResultR\x05order2b\n" +
	"\x0fCheckoutService\x12O\n" +
	"\n" +
	"PlaceOrder\x12\x1e.hipstershop.PlaceOrderRequest\x1a\x1f.hipstershop.PlaceOrderResponse\"\x00B=Z;github.com/netd-tud/ds-onlineshop/proto/checkout;checkoutpbb\x06proto3"

var (
	file_checkout_checkout_proto_rawDescOnce sync.Once
	file_checkout_checkout_proto_rawDescData []byte
)

func file_checkout_checkout_proto_rawDescGZIP() []byte {
	file_checkout_checkout_proto_rawDescOnce.Do(func() {
		file_checkout_checkout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_checkout_checkout_proto_rawDesc), len(file_checkout_checkout_proto_rawDesc)))
	})
	return file_checkout_checkout_proto_rawDescData
}

var file_checkout_checkout_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_checkout_checkout_proto_goTypes = []any{
	(*OrderItem)(nil),              // 0: hipstershop.OrderItem
	(*OrderResult)(nil),            // 1: hipstershop.OrderResult
	(*PlaceOrderRequest)(nil),      // 2: hipstershop.PlaceOrderRequest
	(*PlaceOrderResponse)(nil),     // 3: hipstershop.PlaceOrderResponse
	(*cart.CartItem)(nil),          // 4: hipstershop.CartItem
	(*common.Money)(nil),           // 5: hipstershop.Money
	(*common.Address)(nil),         // 6: hipstershop.Address
	(*payment.CreditCardInfo)(nil), // 7: hipstershop.CreditCardInfo
}
var file_checkout_checkout_proto_depIdxs = []int32{
	4, // 0: hipstershop.OrderItem.item:type_name -> hipstershop.CartItem
	5, // 1: hipstershop.OrderItem.cost:type_name -> hipstershop.Money
	5, // 2: hipstershop.OrderResult.shipping_cost:type_name -> hipstershop.Money
	6, // 3: hipstershop.OrderResult.shipping_address:type_name -> hipstershop.Address
	0, // 4: hipstershop.OrderResult.items:type_name -> hipstershop.OrderItem
	6, // 5: hipstershop.PlaceOrderRequest.address:type_name -> hipstershop.Address
	7, // 6: hipstershop.PlaceOrderRequest.credit_card:type_name -> hipstershop.CreditCardInfo
	1, // 7: hipstershop.PlaceOrderResponse.order:type_name -> hipstershop.OrderResult
	2, // 8: hipstershop.CheckoutService.PlaceOrder:input_type -> hipstershop.PlaceOrderRequest
	3, // 9: hipstershop.CheckoutService.PlaceOrder:output_type -> hipstershop.PlaceOrderResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_checkout_checkout_proto_init() }
func file_checkout_checkout_proto_init() {
	if File_checkout_checkout_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_checkout_checkout_proto_rawDesc), len(file_checkout_checkout_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_checkout_checkout_proto_goTypes,
		DependencyIndexes: file_checkout_checkout_proto_depIdxs,
		MessageInfos:      file_checkout_checkout_proto_msgTypes,
	}.Build()
	File_checkout_checkout_proto = out.File
	file_checkout_checkout_proto_goTypes = nil
	file_checkout_checkout_proto_depIdxs = nil
}
