// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: studentmanagement.proto

package demo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductManagement_UpdateProductStock_FullMethodName = "/student.management.ProductManagement/UpdateProductStock"
	ProductManagement_CreateNewProduct_FullMethodName   = "/student.management.ProductManagement/CreateNewProduct"
)

// ProductManagementClient is the client API for ProductManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductManagementClient interface {
	UpdateProductStock(ctx context.Context, in *ChangeInventoryProductStockRequest, opts ...grpc.CallOption) (*InventoryProduct, error)
	CreateNewProduct(ctx context.Context, in *CreateStudentProductRequest, opts ...grpc.CallOption) (*CreateStudentProductResponse, error)
}

type productManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewProductManagementClient(cc grpc.ClientConnInterface) ProductManagementClient {
	return &productManagementClient{cc}
}

func (c *productManagementClient) UpdateProductStock(ctx context.Context, in *ChangeInventoryProductStockRequest, opts ...grpc.CallOption) (*InventoryProduct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InventoryProduct)
	err := c.cc.Invoke(ctx, ProductManagement_UpdateProductStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productManagementClient) CreateNewProduct(ctx context.Context, in *CreateStudentProductRequest, opts ...grpc.CallOption) (*CreateStudentProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStudentProductResponse)
	err := c.cc.Invoke(ctx, ProductManagement_CreateNewProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductManagementServer is the server API for ProductManagement service.
// All implementations must embed UnimplementedProductManagementServer
// for forward compatibility.
type ProductManagementServer interface {
	UpdateProductStock(context.Context, *ChangeInventoryProductStockRequest) (*InventoryProduct, error)
	CreateNewProduct(context.Context, *CreateStudentProductRequest) (*CreateStudentProductResponse, error)
	mustEmbedUnimplementedProductManagementServer()
}

// UnimplementedProductManagementServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductManagementServer struct{}

func (UnimplementedProductManagementServer) UpdateProductStock(context.Context, *ChangeInventoryProductStockRequest) (*InventoryProduct, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProductStock not implemented")
}
func (UnimplementedProductManagementServer) CreateNewProduct(context.Context, *CreateStudentProductRequest) (*CreateStudentProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNewProduct not implemented")
}
func (UnimplementedProductManagementServer) mustEmbedUnimplementedProductManagementServer() {}
func (UnimplementedProductManagementServer) testEmbeddedByValue()                           {}

// UnsafeProductManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductManagementServer will
// result in compilation errors.
type UnsafeProductManagementServer interface {
	mustEmbedUnimplementedProductManagementServer()
}

func RegisterProductManagementServer(s grpc.ServiceRegistrar, srv ProductManagementServer) {
	// If the following call panics, it indicates UnimplementedProductManagementServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductManagement_ServiceDesc, srv)
}

func _ProductManagement_UpdateProductStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeInventoryProductStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductManagementServer).UpdateProductStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductManagement_UpdateProductStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductManagementServer).UpdateProductStock(ctx, req.(*ChangeInventoryProductStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductManagement_CreateNewProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStudentProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductManagementServer).CreateNewProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductManagement_CreateNewProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductManagementServer).CreateNewProduct(ctx, req.(*CreateStudentProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductManagement_ServiceDesc is the grpc.ServiceDesc for ProductManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "student.management.ProductManagement",
	HandlerType: (*ProductManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateProductStock",
			Handler:    _ProductManagement_UpdateProductStock_Handler,
		},
		{
			MethodName: "CreateNewProduct",
			Handler:    _ProductManagement_CreateNewProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "studentmanagement.proto",
}
