apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ldap.yaml
  - ldap-ui.yaml
  - authservice.yaml

components:
  - ldif

configMapGenerator:
  - name: jwt-public-key
    files:
      - certs/auth_public.pem

secretGenerator:
  - name: jwt-private-key
    files:
      - certs/auth_private.pem

# inject public key into all deployments to decrypt jwt
patches:
  - target:
      kind: Deployment
      name: "^(inventoryservice|frontend)$"
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: unused
      spec:
        template:
          spec:
            containers:
              - name: server
                env:
                - name: JWT_PUBLIC_KEY_PATH
                  value: "/etc/auth/auth_public.pem"
                volumeMounts:
                  - name: jwt-public-key-volume
                    mountPath: "/etc/auth"
                    readOnly: true
            volumes:
              - name: jwt-public-key-volume
                configMap:
                  name: jwt-public-key
