apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ldap.yaml
  - ldap-ui.yaml
  - authservice.yaml

configMapGenerator:
  - name: ldap-bootstrap-ldif
    files:
      - ldif/01-init.ldif
      - ldif/20-readonly.ldif
  - name: ldap-acl-ldif
    files:
      - ldif/10-acl.ldif
  - name: auth-public-key
    files:
      - certs/auth_public.pem

secretGenerator:
  - name: auth-private-key
    files:
      - certs/auth_private.pem
