apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml

components:
- ../../components/container-images-registry

- ../../components/without-loadgenerator
- ../../components/ratingservice
- ../../components/email-via-mqtt
- ../../components/monitoring
- ../../components/dynamic-load-producer
- ../../components/dynamic-load-producer-replicated
- ../../components/warehousemanagement
- ../../components/dtm
- ../../components/auth
- ../../components/kafka

patches:
  - target:
      kind: Deployment
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: unused
      spec:
        template:
          spec:
            imagePullSecrets:
              - name: ghcr-auth
