apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

nameSuffix: -xa

labels:
  - pairs:
      variant: xa
    includeSelectors: true
    includeTemplates: true

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: warehousemanagement
      spec:
        template:
          spec:
            containers:
              - name: server
                env:
                  - name: SERVED_FUNCTION
                    value: "XA"
                  - name: PORT
                    value: "50003"
                  - name: WAREHOUSE_MANAGEMENT_SVC_ADDR
                    value: "warehousemanagement-xa:50003"
                readinessProbe:
                  grpc:
                    port: 50003
                livenessProbe:
                  grpc:
                    port: 50003

  - target:
      kind: Service
      name: warehousemanagement
    patch: |-
      - op: replace
        path: /spec/ports/0/port
        value: 50003
      - op: replace
        path: /spec/ports/0/targetPort
        value: 50003
