apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: dual-role
  namespace: kafka
  labels:
    strimzi.io/cluster: analytics-kafka
spec:
  replicas: 1
  roles: [controller, broker]
  storage:
    type: persistent-claim
    size: 10Gi
    deleteClaim: false
  resources:
    requests: { cpu: "1", memory: 2Gi }
    limits: { cpu: "1.5", memory: 2.5Gi }
  jvmOptions:
    "-Xms": "1g"
    "-Xmx": "1g"
  template:
    pod:
      tolerations:
        - key: dedicated
          operator: Equal
          value: kafka
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload
                    operator: In
                    values: ["kafka"]
