apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: product-events
  namespace: kafka
  labels:
    strimzi.io/cluster: "analytics-kafka"
spec:
  partitions: 8
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: order-events
  namespace: kafka
  labels:
    strimzi.io/cluster: "analytics-kafka"
spec:
  partitions: 8
  replicas: 1
