apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    spec:
      containers:
        - name: server
          env:
            - name: RATING_SERVICE_ADDR
              value: "ratingservice:50001"
