apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - prometheus/prometheus-deployment.yaml
  - grafana/grafana-deployment.yaml
  - cAdvisor/cadvisor-daemonset.yaml

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus/config/scrape_configs.yaml
  - name: grafana-datasources
    files:
      - grafana/provisioning/datasources/datasources.yaml

generatorOptions:
  disableNameSuffixHash: false
