// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: email/email.proto

package emailpb

import (
	common "github.com/turt1z/microservices-demo/src/checkoutservice/genproto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendOrderConfirmationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Order         *common.OrderResult    `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOrderConfirmationRequest) Reset() {
	*x = SendOrderConfirmationRequest{}
	mi := &file_email_email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOrderConfirmationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOrderConfirmationRequest) ProtoMessage() {}

func (x *SendOrderConfirmationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_email_email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOrderConfirmationRequest.ProtoReflect.Descriptor instead.
func (*SendOrderConfirmationRequest) Descriptor() ([]byte, []int) {
	return file_email_email_proto_rawDescGZIP(), []int{0}
}

func (x *SendOrderConfirmationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendOrderConfirmationRequest) GetOrder() *common.OrderResult {
	if x != nil {
		return x.Order
	}
	return nil
}

var File_email_email_proto protoreflect.FileDescriptor

const file_email_email_proto_rawDesc = "" +
	"\n" +
	"\x11email/email.proto\x12\vhipstershop\x1a\x13common/common.proto\"d\n" +
	"\x1cSendOrderConfirmationRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12.\n" +
	"\x05order\x18\x02 \x01(\v2\x18.hipstershop.OrderResultR\x05order2h\n" +
	"\fEmailService\x12X\n" +
	"\x15SendOrderConfirmation\x12).hipstershop.SendOrderConfirmationRequest\x1a\x12.hipstershop.Empty\"\x00B:Z8github.com/turt1z/microservices-demo/proto/email;emailpbb\x06proto3"

var (
	file_email_email_proto_rawDescOnce sync.Once
	file_email_email_proto_rawDescData []byte
)

func file_email_email_proto_rawDescGZIP() []byte {
	file_email_email_proto_rawDescOnce.Do(func() {
		file_email_email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_email_email_proto_rawDesc), len(file_email_email_proto_rawDesc)))
	})
	return file_email_email_proto_rawDescData
}

var file_email_email_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_email_email_proto_goTypes = []any{
	(*SendOrderConfirmationRequest)(nil), // 0: hipstershop.SendOrderConfirmationRequest
	(*common.OrderResult)(nil),           // 1: hipstershop.OrderResult
	(*common.Empty)(nil),                 // 2: hipstershop.Empty
}
var file_email_email_proto_depIdxs = []int32{
	1, // 0: hipstershop.SendOrderConfirmationRequest.order:type_name -> hipstershop.OrderResult
	0, // 1: hipstershop.EmailService.SendOrderConfirmation:input_type -> hipstershop.SendOrderConfirmationRequest
	2, // 2: hipstershop.EmailService.SendOrderConfirmation:output_type -> hipstershop.Empty
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_email_email_proto_init() }
func file_email_email_proto_init() {
	if File_email_email_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_email_email_proto_rawDesc), len(file_email_email_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_email_email_proto_goTypes,
		DependencyIndexes: file_email_email_proto_depIdxs,
		MessageInfos:      file_email_email_proto_msgTypes,
	}.Build()
	File_email_email_proto = out.File
	file_email_email_proto_goTypes = nil
	file_email_email_proto_depIdxs = nil
}
