apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - namespace.yaml
  - configmap.yaml
  - jobmanager.yaml
  - taskmanager.yaml
  - sql-runner-job.yaml

configMapGenerator:
  - name: flink-sql-scripts
    namespace: flink
    files:
      - sql/01_product_analytics.sql
