apiVersion: batch/v1
kind: Job
metadata:
  name: flink-sql-runner
  namespace: flink
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: OnFailure
      tolerations:
        - key: dedicated
          operator: Equal
          value: flink
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload
                    operator: In
                    values: [ "flink" ]
      initContainers:
        - name: wait-and-setup
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - |
              echo "Downloading required jdbc connectors..."

              # 1. Flink JDBC Connector
              curl -sL https://repo1.maven.org/maven2/org/apache/flink/flink-connector-jdbc/3.2.0-1.19/flink-connector-jdbc-3.2.0-1.19.jar \
              -o /flink-lib/flink-connector-jdbc-3.2.0-1.19.jar

              # 2. PostgreSQL JDBC Driver
              curl -sL https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.3/postgresql-42.7.3.jar \
                -o /flink-lib/postgresql-42.7.3.jar

              echo "Fetching Kafka SQL Connector..."
              curl -sL https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-kafka/3.2.0-1.19/flink-sql-connector-kafka-3.2.0-1.19.jar \
                -o /flink-lib/flink-sql-connector-kafka-3.2.0-1.19.jar

              echo "Waiting for Flink JobManager REST API..."
              until curl -s http://flink-jobmanager:8081/v1/overview > /dev/null; do
                sleep 2
              done
              echo "JobManager is ready!"
          volumeMounts:
            - name: flink-lib
              mountPath: /flink-lib
      containers:
        - name: sql-client
          image: flink:1.19.0
          command: ["/docker-entrypoint.sh"]
          args:
            - /bin/bash
            - -c
            - |
              echo "Combining SQL scripts in alphabetical order..."
              cat $(ls /opt/flink/sql/*.sql | sort) > /tmp/combined_jobs.sql

              echo "Combined SQL Payload:"
              cat /tmp/combined_jobs.sql

              echo "Submitting Flink SQL script..."
              /opt/flink/bin/sql-client.sh \
                -j /flink-lib/flink-sql-connector-kafka-3.2.0-1.19.jar \
                -j /flink-lib/flink-connector-jdbc-3.2.0-1.19.jar \
                -j /flink-lib/postgresql-42.7.3.jar \
                -f /tmp/combined_jobs.sql
          envFrom:
            - configMapRef:
                name: flink-config
          volumeMounts:
            - name: flink-sql-scripts
              mountPath: /opt/flink/sql
            - name: flink-lib
              mountPath: /flink-lib
      volumes:
        - name: flink-lib
          emptyDir: {}
        - name: flink-sql-scripts
          configMap:
            name: flink-sql-scripts
