[project]
name = "reorderservice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Florian", email = "florian.zenkel@mailbox.tu-dresden.de" }
]
requires-python = ">=3.14"
dependencies = [
    "grpcio>=1.83.1",
    "grpcio-tools>=1.83.1",
    "python-json-logger>=4.2.0",
]

[project.scripts]
reorderservice = "reorderservice.main:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
