// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: productcatalog/productcatalog.proto

package productcatalogpb

import (
	common "github.com/turt1z/microservices-demo/src/productcatalogservice/genproto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Picture     string                 `protobuf:"bytes,4,opt,name=picture,proto3" json:"picture,omitempty"`
	PriceUsd    *common.Money          `protobuf:"bytes,5,opt,name=price_usd,json=priceUsd,proto3" json:"price_usd,omitempty"`
	// Categories such as "clothing" or "kitchen" that can be used to look up
	// other related products.
	Categories    []string `protobuf:"bytes,6,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_productcatalog_productcatalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_productcatalog_productcatalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_productcatalog_productcatalog_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *Product) GetPriceUsd() *common.Money {
	if x != nil {
		return x.PriceUsd
	}
	return nil
}

func (x *Product) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_productcatalog_productcatalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_productcatalog_productcatalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_productcatalog_productcatalog_proto_rawDescGZIP(), []int{1}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_productcatalog_productcatalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_productcatalog_productcatalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_productcatalog_productcatalog_proto_rawDescGZIP(), []int{2}
}

func (x *GetProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SearchProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductsRequest) Reset() {
	*x = SearchProductsRequest{}
	mi := &file_productcatalog_productcatalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsRequest) ProtoMessage() {}

func (x *SearchProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_productcatalog_productcatalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsRequest.ProtoReflect.Descriptor instead.
func (*SearchProductsRequest) Descriptor() ([]byte, []int) {
	return file_productcatalog_productcatalog_proto_rawDescGZIP(), []int{3}
}

func (x *SearchProductsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Product             `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductsResponse) Reset() {
	*x = SearchProductsResponse{}
	mi := &file_productcatalog_productcatalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsResponse) ProtoMessage() {}

func (x *SearchProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_productcatalog_productcatalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsResponse.ProtoReflect.Descriptor instead.
func (*SearchProductsResponse) Descriptor() ([]byte, []int) {
	return file_productcatalog_productcatalog_proto_rawDescGZIP(), []int{4}
}

func (x *SearchProductsResponse) GetResults() []*Product {
	if x != nil {
		return x.Results
	}
	return nil
}

type CreateNewProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	PriceUsd      *common.Money          `protobuf:"bytes,3,opt,name=price_usd,json=priceUsd,proto3" json:"price_usd,omitempty"`
	Categories    []string               `protobuf:"bytes,4,rep,name=categories,proto3" json:"categories,omitempty"`
	Id            string                 `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"` // used only in DTM-SAGA context. Normally products should be created without providing an ID.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewProductRequest) Reset() {
	*x = CreateNewProductRequest{}
	mi := &file_productcatalog_productcatalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewProductRequest) ProtoMessage() {}

func (x *CreateNewProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_productcatalog_productcatalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewProductRequest.ProtoReflect.Descriptor instead.
func (*CreateNewProductRequest) Descriptor() ([]byte, []int) {
	return file_productcatalog_productcatalog_proto_rawDescGZIP(), []int{5}
}

func (x *CreateNewProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNewProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateNewProductRequest) GetPriceUsd() *common.Money {
	if x != nil {
		return x.PriceUsd
	}
	return nil
}

func (x *CreateNewProductRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *CreateNewProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateNewProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewProductResponse) Reset() {
	*x = CreateNewProductResponse{}
	mi := &file_productcatalog_productcatalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewProductResponse) ProtoMessage() {}

func (x *CreateNewProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_productcatalog_productcatalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewProductResponse.ProtoReflect.Descriptor instead.
func (*CreateNewProductResponse) Descriptor() ([]byte, []int) {
	return file_productcatalog_productcatalog_proto_rawDescGZIP(), []int{6}
}

func (x *CreateNewProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_productcatalog_productcatalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_productcatalog_productcatalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_productcatalog_productcatalog_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductResponse) Reset() {
	*x = DeleteProductResponse{}
	mi := &file_productcatalog_productcatalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductResponse) ProtoMessage() {}

func (x *DeleteProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_productcatalog_productcatalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductResponse) Descriptor() ([]byte, []int) {
	return file_productcatalog_productcatalog_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type XaPrepareCreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           string                 `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	PriceUsd      *common.Money          `protobuf:"bytes,5,opt,name=price_usd,json=priceUsd,proto3" json:"price_usd,omitempty"`
	Categories    []string               `protobuf:"bytes,6,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XaPrepareCreateProductRequest) Reset() {
	*x = XaPrepareCreateProductRequest{}
	mi := &file_productcatalog_productcatalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XaPrepareCreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XaPrepareCreateProductRequest) ProtoMessage() {}

func (x *XaPrepareCreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_productcatalog_productcatalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XaPrepareCreateProductRequest.ProtoReflect.Descriptor instead.
func (*XaPrepareCreateProductRequest) Descriptor() ([]byte, []int) {
	return file_productcatalog_productcatalog_proto_rawDescGZIP(), []int{9}
}

func (x *XaPrepareCreateProductRequest) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *XaPrepareCreateProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *XaPrepareCreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *XaPrepareCreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *XaPrepareCreateProductRequest) GetPriceUsd() *common.Money {
	if x != nil {
		return x.PriceUsd
	}
	return nil
}

func (x *XaPrepareCreateProductRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

var File_productcatalog_productcatalog_proto protoreflect.FileDescriptor

const file_productcatalog_productcatalog_proto_rawDesc = "" +
	"\n" +
	"#productcatalog/productcatalog.proto\x12\vhipstershop\x1a\x13common/common.proto\"\xba\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\apicture\x18\x04 \x01(\tR\apicture\x12/\n" +
	"\tprice_usd\x18\x05 \x01(\v2\x12.hipstershop.MoneyR\bpriceUsd\x12\x1e\n" +
	"\n" +
	"categories\x18\x06 \x03(\tR\n" +
	"categories\"H\n" +
	"\x14ListProductsResponse\x120\n" +
	"\bproducts\x18\x01 \x03(\v2\x14.hipstershop.ProductR\bproducts\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\x15SearchProductsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"H\n" +
	"\x16SearchProductsResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.hipstershop.ProductR\aresults\"\xb0\x01\n" +
	"\x17CreateNewProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12/\n" +
	"\tprice_usd\x18\x03 \x01(\v2\x12.hipstershop.MoneyR\bpriceUsd\x12\x1e\n" +
	"\n" +
	"categories\x18\x04 \x03(\tR\n" +
	"categories\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\"J\n" +
	"\x18CreateNewProductResponse\x12.\n" +
	"\aproduct\x18\x01 \x01(\v2\x14.hipstershop.ProductR\aproduct\"&\n" +
	"\x14DeleteProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"G\n" +
	"\x15DeleteProductResponse\x12.\n" +
	"\aproduct\x18\x01 \x01(\v2\x14.hipstershop.ProductR\aproduct\"\xc8\x01\n" +
	"\x1dXaPrepareCreateProductRequest\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\tR\x03gid\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12/\n" +
	"\tprice_usd\x18\x05 \x01(\v2\x12.hipstershop.MoneyR\bpriceUsd\x12\x1e\n" +
	"\n" +
	"categories\x18\x06 \x03(\tR\n" +
	"categories2\xa2\x06\n" +
	"\x15ProductCatalogService\x12G\n" +
	"\fListProducts\x12\x12.hipstershop.Empty\x1a!.hipstershop.ListProductsResponse\"\x00\x12D\n" +
	"\n" +
	"GetProduct\x12\x1e.hipstershop.GetProductRequest\x1a\x14.hipstershop.Product\"\x00\x12[\n" +
	"\x0eSearchProducts\x12\".hipstershop.SearchProductsRequest\x1a#.hipstershop.SearchProductsResponse\"\x00\x12a\n" +
	"\x10CreateNewProduct\x12$.hipstershop.CreateNewProductRequest\x1a%.hipstershop.CreateNewProductResponse\"\x00\x12X\n" +
	"\rDeleteProduct\x12!.hipstershop.DeleteProductRequest\x1a\".hipstershop.DeleteProductResponse\"\x00\x12h\n" +
	"\x1aCompensateCreateNewProduct\x12$.hipstershop.CreateNewProductRequest\x1a\".hipstershop.DeleteProductResponse\"\x00\x12Z\n" +
	"\x16XaPrepareCreateProduct\x12*.hipstershop.XaPrepareCreateProductRequest\x1a\x12.hipstershop.Empty\"\x00\x12K\n" +
	"\x15XaCommitCreateProduct\x12\x1c.hipstershop.XaBranchRequest\x1a\x12.hipstershop.Empty\"\x00\x12M\n" +
	"\x17XaRollbackCreateProduct\x12\x1c.hipstershop.XaBranchRequest\x1a\x12.hipstershop.Empty\"\x00BLZJgithub.com/turt1z/microservices-demo/proto/productcatalog;productcatalogpbb\x06proto3"

var (
	file_productcatalog_productcatalog_proto_rawDescOnce sync.Once
	file_productcatalog_productcatalog_proto_rawDescData []byte
)

func file_productcatalog_productcatalog_proto_rawDescGZIP() []byte {
	file_productcatalog_productcatalog_proto_rawDescOnce.Do(func() {
		file_productcatalog_productcatalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_productcatalog_productcatalog_proto_rawDesc), len(file_productcatalog_productcatalog_proto_rawDesc)))
	})
	return file_productcatalog_productcatalog_proto_rawDescData
}

var file_productcatalog_productcatalog_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_productcatalog_productcatalog_proto_goTypes = []any{
	(*Product)(nil),                       // 0: hipstershop.Product
	(*ListProductsResponse)(nil),          // 1: hipstershop.ListProductsResponse
	(*GetProductRequest)(nil),             // 2: hipstershop.GetProductRequest
	(*SearchProductsRequest)(nil),         // 3: hipstershop.SearchProductsRequest
	(*SearchProductsResponse)(nil),        // 4: hipstershop.SearchProductsResponse
	(*CreateNewProductRequest)(nil),       // 5: hipstershop.CreateNewProductRequest
	(*CreateNewProductResponse)(nil),      // 6: hipstershop.CreateNewProductResponse
	(*DeleteProductRequest)(nil),          // 7: hipstershop.DeleteProductRequest
	(*DeleteProductResponse)(nil),         // 8: hipstershop.DeleteProductResponse
	(*XaPrepareCreateProductRequest)(nil), // 9: hipstershop.XaPrepareCreateProductRequest
	(*common.Money)(nil),                  // 10: hipstershop.Money
	(*common.Empty)(nil),                  // 11: hipstershop.Empty
	(*common.XaBranchRequest)(nil),        // 12: hipstershop.XaBranchRequest
}
var file_productcatalog_productcatalog_proto_depIdxs = []int32{
	10, // 0: hipstershop.Product.price_usd:type_name -> hipstershop.Money
	0,  // 1: hipstershop.ListProductsResponse.products:type_name -> hipstershop.Product
	0,  // 2: hipstershop.SearchProductsResponse.results:type_name -> hipstershop.Product
	10, // 3: hipstershop.CreateNewProductRequest.price_usd:type_name -> hipstershop.Money
	0,  // 4: hipstershop.CreateNewProductResponse.product:type_name -> hipstershop.Product
	0,  // 5: hipstershop.DeleteProductResponse.product:type_name -> hipstershop.Product
	10, // 6: hipstershop.XaPrepareCreateProductRequest.price_usd:type_name -> hipstershop.Money
	11, // 7: hipstershop.ProductCatalogService.ListProducts:input_type -> hipstershop.Empty
	2,  // 8: hipstershop.ProductCatalogService.GetProduct:input_type -> hipstershop.GetProductRequest
	3,  // 9: hipstershop.ProductCatalogService.SearchProducts:input_type -> hipstershop.SearchProductsRequest
	5,  // 10: hipstershop.ProductCatalogService.CreateNewProduct:input_type -> hipstershop.CreateNewProductRequest
	7,  // 11: hipstershop.ProductCatalogService.DeleteProduct:input_type -> hipstershop.DeleteProductRequest
	5,  // 12: hipstershop.ProductCatalogService.CompensateCreateNewProduct:input_type -> hipstershop.CreateNewProductRequest
	9,  // 13: hipstershop.ProductCatalogService.XaPrepareCreateProduct:input_type -> hipstershop.XaPrepareCreateProductRequest
	12, // 14: hipstershop.ProductCatalogService.XaCommitCreateProduct:input_type -> hipstershop.XaBranchRequest
	12, // 15: hipstershop.ProductCatalogService.XaRollbackCreateProduct:input_type -> hipstershop.XaBranchRequest
	1,  // 16: hipstershop.ProductCatalogService.ListProducts:output_type -> hipstershop.ListProductsResponse
	0,  // 17: hipstershop.ProductCatalogService.GetProduct:output_type -> hipstershop.Product
	4,  // 18: hipstershop.ProductCatalogService.SearchProducts:output_type -> hipstershop.SearchProductsResponse
	6,  // 19: hipstershop.ProductCatalogService.CreateNewProduct:output_type -> hipstershop.CreateNewProductResponse
	8,  // 20: hipstershop.ProductCatalogService.DeleteProduct:output_type -> hipstershop.DeleteProductResponse
	8,  // 21: hipstershop.ProductCatalogService.CompensateCreateNewProduct:output_type -> hipstershop.DeleteProductResponse
	11, // 22: hipstershop.ProductCatalogService.XaPrepareCreateProduct:output_type -> hipstershop.Empty
	11, // 23: hipstershop.ProductCatalogService.XaCommitCreateProduct:output_type -> hipstershop.Empty
	11, // 24: hipstershop.ProductCatalogService.XaRollbackCreateProduct:output_type -> hipstershop.Empty
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_productcatalog_productcatalog_proto_init() }
func file_productcatalog_productcatalog_proto_init() {
	if File_productcatalog_productcatalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_productcatalog_productcatalog_proto_rawDesc), len(file_productcatalog_productcatalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_productcatalog_productcatalog_proto_goTypes,
		DependencyIndexes: file_productcatalog_productcatalog_proto_depIdxs,
		MessageInfos:      file_productcatalog_productcatalog_proto_msgTypes,
	}.Build()
	File_productcatalog_productcatalog_proto = out.File
	file_productcatalog_productcatalog_proto_goTypes = nil
	file_productcatalog_productcatalog_proto_depIdxs = nil
}
