apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventoryservice
  labels:
    app: inventoryservice
spec:
  selector:
    matchLabels:
      app: inventoryservice
  template:
    metadata:
      labels:
        app: inventoryservice
    spec:
      serviceAccountName: inventoryservice
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: ghcr.io/turt1z/microservices-demo/inventoryservice:latest
          ports:
            - containerPort: 50002
          env:
            - name: PORT
              value: "50002"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "productcatalogservice:3550"
            - name: MQTT_BROKER_ADDR
              value: "mqtt-broker:1883"
          readinessProbe:
            grpc:
              port: 50002
          livenessProbe:
            grpc:
              port: 50002
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: inventoryservice
  labels:
    app: inventoryservice
spec:
  type: ClusterIP
  selector:
    app: inventoryservice
  ports:
    - name: grpc
      port: 50002
      targetPort: 50002
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventoryservice
