syntax = "proto3";

package hipstershop;

option go_package = "github.com/netd-tud/ds-onlineshop/proto/notification;notificationpb";

// ------------Notification service------------------

service NotificationService {
  rpc ListOpenAlerts(ListOpenAlertsRequest) returns (ListOpenAlertsResponse) {}
}

message ListOpenAlertsRequest { repeated string categories = 1; }

message StockAlert {
  string product_id = 1;
  repeated string category = 2;
  int64 stock = 3;
  string severity = 4;
}

message ListOpenAlertsResponse { repeated StockAlert alerts = 1; }
