syntax = "proto3";

package hipstershop;

option go_package = "github.com/netd-tud/ds-onlineshop/proto/notification;notificationpb";

import "checkout/checkout.proto";

// ------------Notification service------------------

service NotificationService {
  rpc ListOpenAlerts(ListOpenAlertsRequest) returns (ListOpenAlertsResponse) {}
  rpc ListRecentOrdersByCurrency(ListRecentOrdersByCurrencyRequest) returns (ListRecentOrdersByCurrencyResponse) {}
}

message ListOpenAlertsRequest { repeated string categories = 1; }

message StockAlert {
  string product_id = 1;
  repeated string category = 2;
  int64 stock = 3;
  string severity = 4;
}

message ListOpenAlertsResponse { repeated StockAlert alerts = 1; }

message ListRecentOrdersByCurrencyRequest { repeated string currency = 1; }

message ListRecentOrdersByCurrencyResponse { repeated OrderResult orders = 1; }
