// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: inventory/inventory.proto

package inventorypb

import (
	context "context"
	common "github.com/turt1z/microservices-demo/src/inventoryservice/genproto/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryService_ListInventory_FullMethodName                       = "/hipstershop.InventoryService/ListInventory"
	InventoryService_GetInventoryProduct_FullMethodName                 = "/hipstershop.InventoryService/GetInventoryProduct"
	InventoryService_ChangeInventoryProductStock_FullMethodName         = "/hipstershop.InventoryService/ChangeInventoryProductStock"
	InventoryService_SetInventoryProductStock_FullMethodName            = "/hipstershop.InventoryService/SetInventoryProductStock"
	InventoryService_CreateNewInventoryProduct_FullMethodName           = "/hipstershop.InventoryService/CreateNewInventoryProduct"
	InventoryService_DeleteInventoryProduct_FullMethodName              = "/hipstershop.InventoryService/DeleteInventoryProduct"
	InventoryService_CompensateCreateNewInventoryProduct_FullMethodName = "/hipstershop.InventoryService/CompensateCreateNewInventoryProduct"
	InventoryService_XaPrepareCreateInventoryProduct_FullMethodName     = "/hipstershop.InventoryService/XaPrepareCreateInventoryProduct"
	InventoryService_XaCommitCreateInventoryProduct_FullMethodName      = "/hipstershop.InventoryService/XaCommitCreateInventoryProduct"
	InventoryService_XaRollbackCreateInventoryProduct_FullMethodName    = "/hipstershop.InventoryService/XaRollbackCreateInventoryProduct"
)

// InventoryServiceClient is the client API for InventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryServiceClient interface {
	ListInventory(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*ListInventoryResponse, error)
	GetInventoryProduct(ctx context.Context, in *GetInventoryProductRequest, opts ...grpc.CallOption) (*InventoryProduct, error)
	ChangeInventoryProductStock(ctx context.Context, in *ChangeInventoryProductStockRequest, opts ...grpc.CallOption) (*ChangeInventoryProductStockResponse, error)
	SetInventoryProductStock(ctx context.Context, in *SetInventoryProductStockRequest, opts ...grpc.CallOption) (*SetInventoryProductStockRequestResponse, error)
	CreateNewInventoryProduct(ctx context.Context, in *CreateNewInventoryProductRequest, opts ...grpc.CallOption) (*CreateNewInventoryProductResponse, error)
	DeleteInventoryProduct(ctx context.Context, in *DeleteInventoryProductRequest, opts ...grpc.CallOption) (*DeleteInventoryProductResponse, error)
	// SAGA compensation adapter for CreateNewProduct. Accepts the same payload as CreateNewProduct
	// because DTM resends the original action's request bytes when invoking the compensating transaction.
	CompensateCreateNewInventoryProduct(ctx context.Context, in *CreateNewInventoryProductRequest, opts ...grpc.CallOption) (*DeleteInventoryProductResponse, error)
	// XA
	XaPrepareCreateInventoryProduct(ctx context.Context, in *XaPrepareCreateInventoryProductRequest, opts ...grpc.CallOption) (*common.Empty, error)
	XaCommitCreateInventoryProduct(ctx context.Context, in *common.XaBranchRequest, opts ...grpc.CallOption) (*common.Empty, error)
	XaRollbackCreateInventoryProduct(ctx context.Context, in *common.XaBranchRequest, opts ...grpc.CallOption) (*common.Empty, error)
}

type inventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryServiceClient(cc grpc.ClientConnInterface) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) ListInventory(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*ListInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInventoryResponse)
	err := c.cc.Invoke(ctx, InventoryService_ListInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) GetInventoryProduct(ctx context.Context, in *GetInventoryProductRequest, opts ...grpc.CallOption) (*InventoryProduct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InventoryProduct)
	err := c.cc.Invoke(ctx, InventoryService_GetInventoryProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ChangeInventoryProductStock(ctx context.Context, in *ChangeInventoryProductStockRequest, opts ...grpc.CallOption) (*ChangeInventoryProductStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeInventoryProductStockResponse)
	err := c.cc.Invoke(ctx, InventoryService_ChangeInventoryProductStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) SetInventoryProductStock(ctx context.Context, in *SetInventoryProductStockRequest, opts ...grpc.CallOption) (*SetInventoryProductStockRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetInventoryProductStockRequestResponse)
	err := c.cc.Invoke(ctx, InventoryService_SetInventoryProductStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) CreateNewInventoryProduct(ctx context.Context, in *CreateNewInventoryProductRequest, opts ...grpc.CallOption) (*CreateNewInventoryProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNewInventoryProductResponse)
	err := c.cc.Invoke(ctx, InventoryService_CreateNewInventoryProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) DeleteInventoryProduct(ctx context.Context, in *DeleteInventoryProductRequest, opts ...grpc.CallOption) (*DeleteInventoryProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteInventoryProductResponse)
	err := c.cc.Invoke(ctx, InventoryService_DeleteInventoryProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) CompensateCreateNewInventoryProduct(ctx context.Context, in *CreateNewInventoryProductRequest, opts ...grpc.CallOption) (*DeleteInventoryProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteInventoryProductResponse)
	err := c.cc.Invoke(ctx, InventoryService_CompensateCreateNewInventoryProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) XaPrepareCreateInventoryProduct(ctx context.Context, in *XaPrepareCreateInventoryProductRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, InventoryService_XaPrepareCreateInventoryProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) XaCommitCreateInventoryProduct(ctx context.Context, in *common.XaBranchRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, InventoryService_XaCommitCreateInventoryProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) XaRollbackCreateInventoryProduct(ctx context.Context, in *common.XaBranchRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, InventoryService_XaRollbackCreateInventoryProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServiceServer is the server API for InventoryService service.
// All implementations must embed UnimplementedInventoryServiceServer
// for forward compatibility.
type InventoryServiceServer interface {
	ListInventory(context.Context, *common.Empty) (*ListInventoryResponse, error)
	GetInventoryProduct(context.Context, *GetInventoryProductRequest) (*InventoryProduct, error)
	ChangeInventoryProductStock(context.Context, *ChangeInventoryProductStockRequest) (*ChangeInventoryProductStockResponse, error)
	SetInventoryProductStock(context.Context, *SetInventoryProductStockRequest) (*SetInventoryProductStockRequestResponse, error)
	CreateNewInventoryProduct(context.Context, *CreateNewInventoryProductRequest) (*CreateNewInventoryProductResponse, error)
	DeleteInventoryProduct(context.Context, *DeleteInventoryProductRequest) (*DeleteInventoryProductResponse, error)
	// SAGA compensation adapter for CreateNewProduct. Accepts the same payload as CreateNewProduct
	// because DTM resends the original action's request bytes when invoking the compensating transaction.
	CompensateCreateNewInventoryProduct(context.Context, *CreateNewInventoryProductRequest) (*DeleteInventoryProductResponse, error)
	// XA
	XaPrepareCreateInventoryProduct(context.Context, *XaPrepareCreateInventoryProductRequest) (*common.Empty, error)
	XaCommitCreateInventoryProduct(context.Context, *common.XaBranchRequest) (*common.Empty, error)
	XaRollbackCreateInventoryProduct(context.Context, *common.XaBranchRequest) (*common.Empty, error)
	mustEmbedUnimplementedInventoryServiceServer()
}

// UnimplementedInventoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryServiceServer struct{}

func (UnimplementedInventoryServiceServer) ListInventory(context.Context, *common.Empty) (*ListInventoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInventory not implemented")
}
func (UnimplementedInventoryServiceServer) GetInventoryProduct(context.Context, *GetInventoryProductRequest) (*InventoryProduct, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInventoryProduct not implemented")
}
func (UnimplementedInventoryServiceServer) ChangeInventoryProductStock(context.Context, *ChangeInventoryProductStockRequest) (*ChangeInventoryProductStockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeInventoryProductStock not implemented")
}
func (UnimplementedInventoryServiceServer) SetInventoryProductStock(context.Context, *SetInventoryProductStockRequest) (*SetInventoryProductStockRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetInventoryProductStock not implemented")
}
func (UnimplementedInventoryServiceServer) CreateNewInventoryProduct(context.Context, *CreateNewInventoryProductRequest) (*CreateNewInventoryProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNewInventoryProduct not implemented")
}
func (UnimplementedInventoryServiceServer) DeleteInventoryProduct(context.Context, *DeleteInventoryProductRequest) (*DeleteInventoryProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteInventoryProduct not implemented")
}
func (UnimplementedInventoryServiceServer) CompensateCreateNewInventoryProduct(context.Context, *CreateNewInventoryProductRequest) (*DeleteInventoryProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompensateCreateNewInventoryProduct not implemented")
}
func (UnimplementedInventoryServiceServer) XaPrepareCreateInventoryProduct(context.Context, *XaPrepareCreateInventoryProductRequest) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method XaPrepareCreateInventoryProduct not implemented")
}
func (UnimplementedInventoryServiceServer) XaCommitCreateInventoryProduct(context.Context, *common.XaBranchRequest) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method XaCommitCreateInventoryProduct not implemented")
}
func (UnimplementedInventoryServiceServer) XaRollbackCreateInventoryProduct(context.Context, *common.XaBranchRequest) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method XaRollbackCreateInventoryProduct not implemented")
}
func (UnimplementedInventoryServiceServer) mustEmbedUnimplementedInventoryServiceServer() {}
func (UnimplementedInventoryServiceServer) testEmbeddedByValue()                          {}

// UnsafeInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServiceServer will
// result in compilation errors.
type UnsafeInventoryServiceServer interface {
	mustEmbedUnimplementedInventoryServiceServer()
}

func RegisterInventoryServiceServer(s grpc.ServiceRegistrar, srv InventoryServiceServer) {
	// If the following call panics, it indicates UnimplementedInventoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryService_ServiceDesc, srv)
}

func _InventoryService_ListInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ListInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ListInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ListInventory(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_GetInventoryProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInventoryProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetInventoryProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_GetInventoryProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetInventoryProduct(ctx, req.(*GetInventoryProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ChangeInventoryProductStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeInventoryProductStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ChangeInventoryProductStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ChangeInventoryProductStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ChangeInventoryProductStock(ctx, req.(*ChangeInventoryProductStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_SetInventoryProductStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetInventoryProductStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).SetInventoryProductStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_SetInventoryProductStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).SetInventoryProductStock(ctx, req.(*SetInventoryProductStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_CreateNewInventoryProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewInventoryProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).CreateNewInventoryProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_CreateNewInventoryProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).CreateNewInventoryProduct(ctx, req.(*CreateNewInventoryProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_DeleteInventoryProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInventoryProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).DeleteInventoryProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_DeleteInventoryProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).DeleteInventoryProduct(ctx, req.(*DeleteInventoryProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_CompensateCreateNewInventoryProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewInventoryProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).CompensateCreateNewInventoryProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_CompensateCreateNewInventoryProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).CompensateCreateNewInventoryProduct(ctx, req.(*CreateNewInventoryProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_XaPrepareCreateInventoryProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(XaPrepareCreateInventoryProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).XaPrepareCreateInventoryProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_XaPrepareCreateInventoryProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).XaPrepareCreateInventoryProduct(ctx, req.(*XaPrepareCreateInventoryProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_XaCommitCreateInventoryProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.XaBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).XaCommitCreateInventoryProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_XaCommitCreateInventoryProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).XaCommitCreateInventoryProduct(ctx, req.(*common.XaBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_XaRollbackCreateInventoryProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.XaBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).XaRollbackCreateInventoryProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_XaRollbackCreateInventoryProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).XaRollbackCreateInventoryProduct(ctx, req.(*common.XaBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryService_ServiceDesc is the grpc.ServiceDesc for InventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hipstershop.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListInventory",
			Handler:    _InventoryService_ListInventory_Handler,
		},
		{
			MethodName: "GetInventoryProduct",
			Handler:    _InventoryService_GetInventoryProduct_Handler,
		},
		{
			MethodName: "ChangeInventoryProductStock",
			Handler:    _InventoryService_ChangeInventoryProductStock_Handler,
		},
		{
			MethodName: "SetInventoryProductStock",
			Handler:    _InventoryService_SetInventoryProductStock_Handler,
		},
		{
			MethodName: "CreateNewInventoryProduct",
			Handler:    _InventoryService_CreateNewInventoryProduct_Handler,
		},
		{
			MethodName: "DeleteInventoryProduct",
			Handler:    _InventoryService_DeleteInventoryProduct_Handler,
		},
		{
			MethodName: "CompensateCreateNewInventoryProduct",
			Handler:    _InventoryService_CompensateCreateNewInventoryProduct_Handler,
		},
		{
			MethodName: "XaPrepareCreateInventoryProduct",
			Handler:    _InventoryService_XaPrepareCreateInventoryProduct_Handler,
		},
		{
			MethodName: "XaCommitCreateInventoryProduct",
			Handler:    _InventoryService_XaCommitCreateInventoryProduct_Handler,
		},
		{
			MethodName: "XaRollbackCreateInventoryProduct",
			Handler:    _InventoryService_XaRollbackCreateInventoryProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory/inventory.proto",
}
