apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
components:
 - ../../components/without-loadgenerator
 - ../../components/ratingservice
 - ../../components/local-dev-images
 - ../../components/email-via-mqtt
